// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc190.FRC2k15.subsystems;

import org.usfirst.frc190.FRC2k15.RobotMap;
import org.usfirst.frc190.FRC2k15.Components.LimitedPIDSubsystem;

import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 *
 */
public class TineElevator extends PIDSubsystem implements LimitedPIDSubsystem{
	// TODO: Update These
	public double bottomPosition = 0.0;
	public double topPosition = 0.0;
	public double humanLoadPosition = 0.0;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    AnalogPotentiometer elevatorPot = RobotMap.tineElevatorelevatorPot;
    SpeedController elevator = RobotMap.tineElevatorelevator;
    DigitalInput topLimit = RobotMap.tineElevatortopLimit;
    DigitalInput lowerLimit = RobotMap.tineElevatorlowerLimit;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	// Initialize your subsystem here
	public TineElevator() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        super("TineElevator", 1.0, 0.0, 0.0);
        setAbsoluteTolerance(0.2);
        getPIDController().setContinuous(false);
        LiveWindow.addActuator("TineElevator", "PIDSubsystem Controller", getPIDController());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
	}

	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	}

	protected double returnPIDInput() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
        return elevatorPot.get();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
	}

	protected void usePIDOutput(double output) {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
        elevator.pidWrite(output);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
	}

	/**
	 * @param speed
	 *            Speed to set the motor to
	 */
	public void setSpeed(double speed) {
		disable();
		elevator.set(speed);
	}

	public boolean getTopLimit() {
//		return topLimit.get();
		return false;
	}

	public boolean getLowerLimit() {
//		return lowerLimit.get();
		return false;
	}

	@Override
	public boolean atmax() {
//		return topLimit.get();
		return false;
	}

	@Override
	public boolean atmin() {
//		return lowerLimit.get();
		return false;
	}

	@Override
	public void setPosition(double setpoint) {
		enable();
		setSetpoint(setpoint);
	}

	@Override
	public boolean atPosition() {
		return onTarget();
	}

	@Override
	public PIDSubsystem getSubSystem() {
		return this;
	}
}
