// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc190.FRC2k15.commands;
import org.usfirst.frc190.FRC2k15.Robot;
import org.usfirst.frc190.FRC2k15.Components.LimitedPIDSubsystemSetpointCommand;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Auto1RC extends CommandGroup {
    
    public  Auto1RC() {
    	
//Starts with tines closed and touching RC. 
//Elevator starts beneath the lip of the RC.
    	//Lifts RC to middle and then drives to the left. 
    	
    	addSequential(new LimitedPIDSubsystemSetpointCommand(Robot.tineElevator, Robot.tineElevator.midPosition, 0.8, -0.8, false));
    	addSequential(new DriveDistDirection(0.3, 72, 270));
    	
    	
    }
}
