// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc190.FRC2k15.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *Basic drive forwards auto command group
 */
public class AutoDriveForward extends CommandGroup {
    
    public  AutoDriveForward() {

    	
    	//Reset Chainsaw so it is zeroed for the match;
    	addParallel(new ResetChainsaw());
    	//Drive into auto zone
    	addSequential(new DriveDistDirection(0.75, 48, 0), 7);	//Timeout of 7 seconds
    }
}
