// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc190.FRC2k15.commands;
import org.usfirst.frc190.FRC2k15.Robot;
import org.usfirst.frc190.FRC2k15.Components.LimitedPIDSubsystemSetpointCommand;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutoStealContainers extends CommandGroup {
    
    public  AutoStealContainers() {
    	//Reset Chainsaw so it is zeroed for the match;
    	addParallel(new ResetChainsaw());
    	//Drive backwards to step
    	addSequential(new DriveDistDirection(0.5, 54, 180));
    	//Wait for balls to fall in
    	addSequential(new Delay(2));
    	//drive forward into autozone
    	addSequential(new DriveDistDirection(0.5, 96, 0), 8);	//Timeout of 8 seconds
    	//TODO: Test This
    	//Extend Chainsaw 4-Bar to close WOD
    	//addSequential(new LimitedPIDSubsystemSetpointCommand(Robot.chainsaw4Bar,Robot.chainsaw4Bar.scoringPosition, true), 2);			//Timeout of 2 seconds
    	//Retract Chainsaw
    	//addSequential(new LimitedPIDSubsystemSetpointCommand(Robot.chainsaw4Bar,Robot.chainsaw4Bar.storagePosition, true), 2);			//Timeout of 2 seconds
    }
}
