// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc190.FRC2k15.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class DriveDistTestSequence extends CommandGroup {
    
    public  DriveDistTestSequence() {
    	addSequential(new DriveDistDirection(0.2, 24, 0));
    	addSequential(new DriveDistDirection(0.2, 24, 90));
    	addSequential(new DriveDistDirection(0.2, 24, 180));
    	addSequential(new DriveDistDirection(0.2, 24, 270));
    }
}
