// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc190.FRC2k15.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc190.FRC2k15.RobotMap;
import org.usfirst.frc190.FRC2k15.Components.I2Cgyro;

/**
 *
 */
public class  GyroUpdate extends Command {
private I2Cgyro gyro;
    public GyroUpdate() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	gyro = RobotMap.gyro; //save the gyro object
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	gyro.update();//update the gyro
    	SmartDashboard.putNumber("Rate", gyro.getZRate());//just for testing be deleted after
    	SmartDashboard.putNumber("Angle", gyro.getHeading());
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;//never ends
    }

    // Called once after isFinished returns true
    protected void end() {//doesn't end and has nothing to do when it ends anyways
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {//no subsystems required so never will be interrupted
    }
}
