// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc190.FRC2k15.commands;

import org.usfirst.frc190.FRC2k15.OI;
import org.usfirst.frc190.FRC2k15.Robot;
import org.usfirst.frc190.FRC2k15.Components.VoiceCmds;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */

public class RegularDriveToLimit extends Command {
	
	private final double toteSpeedLimit = 0.5;

	public RegularDriveToLimit() {
		// Use requires() here to declare subsystem dependencies
		// eg. requires(chassis);

		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drivetrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}

	// Called just before this Command runs the first time
	protected void initialize() {
		VoiceCmds.speak(VoiceCmds.d_teleDrive);
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute() {
		final double rotationLimit = 0.6; //0.5;

		double xSpeed;
		double ySpeed;
		double rSpeed;
		double heading = Robot.drivetrain.getHeading();
		//(double deadbandWidth, double minValue, double value)
		xSpeed = OI.deadband(0.3, 0.08, Robot.oi.driveJoystick.getX());
		ySpeed = OI.deadband(0.3, 0.08, Robot.oi.driveJoystick.getY());
		switch (Robot.drivetrain.getDrivingMode()) {
		case 0:
			rSpeed = OI.deadband(0.5, 0.08, Robot.oi.driveJoystick.getZ());
			break;

		case 1:
			rSpeed = OI.deadband(0.3, 0.08, Robot.oi.secondaryJoystick.getX());
			break;

		case 2:
			rSpeed = OI.deadband(0.3, 0.08, Robot.oi.secondaryJoystick.getY());
			break;

		case 3:
			rSpeed = OI.deadband(0.5, 0.08, Robot.oi.secondaryJoystick.getZ());
			break;
			
		case 4:
			xSpeed = OI.deadband(0.3, 0.08, Robot.oi.secondaryJoystick.getX());
			ySpeed = OI.deadband(0.3, 0.08, Robot.oi.secondaryJoystick.getY());
			rSpeed = OI.deadband(0.5, 0.08, Robot.oi.secondaryJoystick.getZ());
			break;

		default:
			rSpeed = OI.deadband(0.5, 0.08, Robot.oi.driveJoystick.getZ());
			break;
		}
		
		//Slow rotation speed
		rSpeed = rSpeed*rotationLimit;
		
		if (Robot.drivetrain.isSquaredInputs()) {
			xSpeed = Math.pow(Math.abs(xSpeed), 2) * Math.signum(xSpeed);
			ySpeed = Math.pow(Math.abs(ySpeed), 2) * Math.signum(ySpeed);
			rSpeed = Math.pow(Math.abs(rSpeed), 2) * Math.signum(rSpeed);
		}

		if (!Robot.drivetrain.isFieldOriented()) {
			heading = 0;
		}
		
		if(Robot.chainsaw.getHookPosition() > 0){
			xSpeed = xSpeed*toteSpeedLimit;
			ySpeed = ySpeed*toteSpeedLimit;
		}

		Robot.drivetrain.MecanumDrive(xSpeed, ySpeed, rSpeed, heading);

	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished() {
		return Robot.drivetrain.getLeftBumper() || Robot.drivetrain.getRightBumper();
	}

	// Called once after isFinished returns true
	protected void end() {
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted() {
	}

}
